### ISSUE TITLE
Not allowing to download datasets 

### ISSUE THREAD

**Issue by MuhammadAnns** [hacetin/deep-triage#2]
I am trying to download datasets in repository, it redirects me to Google Drive link where it shows message that "File is in owner's trash". As you can also see under "Download Permission" section in attached screenshot, it says "Viewers cannot download"

![Screenshot from 2020-05-17 08-10-50](https://user-images.githubusercontent.com/10582397/82134878-f3c91c00-9815-11ea-820a-37825e81a9e0.png)

It would be a huge help if you grant me permissions to download datasets.

**Comment by emredogan7** [comment]
Hi there,

I am afraid we are not the ones that you should ask for the download permission. I just checked our links and noticed that we shared the original links given in the [paper website](http://bugtriage.mybluemix.net/). 

You can contact with the paper authors for another way to download dataset files.

**Comment by MuhammadAnns** [comment]
Hi emredogan7,

How can i contact admin of paper website as i cannot find any contact information on their website. Can you please guide me ?

**Comment by emredogan7** [comment]
You can find their email addresses in the paper.
